version: "3.9"
services:
    php:
        # image: php:8.3-fpm
        build: 
            dockerfile: ./docker/Dockerfile
        container_name: php
        restart: unless-stopped
        expose:
            - 9000:9000
        volumes:
            - .:/var/www/

    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - .:/var/www/
            - ./docker/config/nginx.conf:/etc/nginx/nginx.conf:ro

    db:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        ports:
            - 3306:3306
        volumes: 
            - data:/var/lib/mysql
            # - .docker/db/data:/var/lib/mysql
            # - .docker/logs:/var/log/mysql
            # - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            # - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:  
            MYSQL_ROOT_PASSWORD: huyFTYt12_
            MYSQL_DATABASE: test
volumes:
    data: